services:
  frontend:
    build: frontend
    ports:
      - "127.0.0.1:4477:5173"

  puzzle-generator:
    build:
      context: puzzle-generator
      tags:
        - "unlock-puzzle-generator"

  svg-to-png:
    build:
      context: svg-to-png
      tags:
        - "unlock-svg-to-png"

  pngs-to-gif:
    build:
      context: pngs-to-gif
      tags:
        - "pngs-to-gif"
