[package]
name = "pngs-to-gif"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.89"
image = { version = "0.24.9", features = ["gif"] }
js-sys = "0.3.68"
hex = "0.4.3"
